# Generated by Django 5.1.3 on 2025-02-15 06:43

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_member_faculty_chatmessage_delete_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='post_video',
            field=models.FileField(blank=True, default='', null=True, upload_to='post_videos/'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='', force_format='JPEG', keep_meta=False, null=True, quality=60, scale=0.5, size=[1280, 720], upload_to='post_images/'),
        ),
    ]
