# Generated by Django 5.1.3 on 2025-06-06 19:48

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_posts_post_video_alter_posts_post_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='qr_code',
            field=django_resized.forms.ResizedImageField(crop=None, default='default.webp', force_format='JPEG', keep_meta=False, quality=95, scale=0.5, size=[1080, 1080], upload_to='qr_images/'),
        ),
    ]
