# Generated by Django 5.1.3 on 2025-05-15 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='group',
        ),
    ]
