# Generated by Django 5.1.3 on 2025-05-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_posts_post_video_alter_posts_post_picture'),
        ('transactions', '0003_transaction_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='involved_members',
            field=models.ManyToManyField(related_name='involved_transactions', to='core.member'),
        ),
    ]
