# Generated by Django 5.1.3 on 2025-05-15 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_posts_post_video_alter_posts_post_picture'),
        ('transactions', '0004_alter_transaction_involved_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultliability',
            name='user',
            field=models.ForeignKey(limit_choices_to={'member_groups__isnull': False}, on_delete=django.db.models.deletion.PROTECT, to='core.member'),
        ),
        migrations.AlterField(
            model_name='membergroup',
            name='members',
            field=models.ManyToManyField(related_name='member_groups', to='core.member'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='initiated_by',
            field=models.ForeignKey(limit_choices_to={'member_groups__isnull': False}, on_delete=django.db.models.deletion.PROTECT, related_name='initiated_transactions', to='core.member'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='involved_members',
            field=models.ManyToManyField(limit_choices_to={'member_groups__isnull': False}, related_name='involved_transactions', to='core.member'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='paid_by',
            field=models.ForeignKey(limit_choices_to={'member_groups__isnull': False}, on_delete=django.db.models.deletion.PROTECT, related_name='paid_transactions', to='core.member'),
        ),
    ]
