# Generated by Django 5.1.3 on 2025-05-15 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_ledgerentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='transactions.transaction'),
        ),
    ]
