# Generated by Django 5.1.3 on 2025-06-06 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_member_qr_code'),
        ('transactions', '0008_ledgerentry_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultliability',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.membergroup'),
        ),
        migrations.AlterField(
            model_name='defaultliability',
            name='user',
            field=models.ForeignKey(limit_choices_to={'member_groups__isnull': False}, on_delete=django.db.models.deletion.CASCADE, to='core.member'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='transactions.membergroup'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='core.member'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.membergroup'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_made', to='core.member'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_received', to='core.member'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='transactions.membergroup'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='initiated_by',
            field=models.ForeignKey(limit_choices_to={'member_groups__isnull': False}, on_delete=django.db.models.deletion.CASCADE, related_name='initiated_transactions', to='core.member'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='paid_by',
            field=models.ForeignKey(limit_choices_to={'member_groups__isnull': False}, on_delete=django.db.models.deletion.CASCADE, related_name='paid_transactions', to='core.member'),
        ),
    ]
